# Site settings
title: Jonathon Harrelson
email: jonathon@jonathon-harrelson.com
description: A front-end web developer located in Houston, Texas. Jonathon also specializes in search engine optimization and seaking to others about the web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: MrJHarrelson
github_username:  Daygon2007

# Build settings
markdown: kramdown

#Setting Permalinks
permalink: /:categories/:title/
sass: 
  style: compressed

# Navigation
navigation:
- root: Home
  url:
  icon: icon-you-want
  
- root: Portfolio
  url: /portfolio/
  
- root: My Story
  url: /my-story/

- root: Contact Me
  url: /contact/

- root: Blog
  url: /blog/
  
- root: Download My FREE E-Book
  url: /docs/guess-what.pdf
  
# Excerpts
excerpt_separator: <a href="{ site.url }{ post.url }">Read More @rarr;</a>